### ISSUE TITLE
Trakt movies sync error UTC+1 on Microsoft OS (Windows11 & Xbox Series X)

### ISSUE THREAD

**Issue by AwakenCX** [trakt/script.trakt#658]
Hello everyone,

first of all I'd like to say that I've tried every trick I could find but I still have a problem whether it's on Xbox or Windows.

I can't synchronize my movies (TV series are ok).

The loading bar freezes at 3/4 on “the playback counter of 259 movies will be updated in Kodi”.

I use Kodi in French, I also tried to change the interface to English. I have all the graphic settings by default.

I've already tried replacing my UTC+1 (Paris) on Windows with a dozen other options (but maybe not THE right one) with no result.

I've already tried replacing the “script.module.dateutil” plugin with the one on this site, and it's in version 2.8.2.

I have no problem with my Android TV for Trakt, but it doesn't support 4K..

## Steps to Reproduce (for bugs)

1. Just try to sync trakt movies

## Environment
* Version used: 3.6.1 (also try 3.7.0 from git)
* Kodi version used: Kodi (21.1 (21.1.0) Git:20240817-183eb85f10)
* Operating System and version: Windows 11 and also Xbox Series X
* CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 16 cores available
* RAM : 32.0 GB

## Logs

```

2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2, C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py): the source file to load is "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py"
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2): full python path:
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):   custom python path:
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.arrow\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.certifi\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.chardet\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.dateutil\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.idna\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.requests\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.six\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.trakt\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.typing_extensions\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.urllib3\lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):   default python path:
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.1.500.0_x64__4n2hpmxwrvr6p\system\python\DLLs
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.1.500.0_x64__4n2hpmxwrvr6p\system\python\Lib
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):     C:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.1.500.0_x64__4n2hpmxwrvr6p\system\python\Lib\site-packages
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2): adding args:
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2):  defaultscript.py
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2, C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py): entering source directory C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt
2024-10-04 15:58:35.651 T:3612    debug <general>: CPythonInvoker(2, C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py): instantiating addon using automatically obtained id of "script.trakt" dependent on version 3.0.0 of the xbmc.python api
2024-10-04 15:58:35.883 T:3612     info <general>: start trakt with arguments: {'action': 'sync'}
2024-10-04 15:58:35.889 T:3612    debug <general>: CPythonInvoker(2, C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py): script successfully run
2024-10-04 15:58:35.889 T:3612    debug <general>: CPythonInvoker::onExecutionDone(2, C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py)
2024-10-04 15:58:35.895 T:3612    debug <general>: .
2024-10-04 15:58:35.903 T:3612    debug <general>: Python interpreter stopped
2024-10-04 15:58:35.903 T:3612    debug <general>: Thread LanguageInvoker 3612 terminating
2024-10-04 15:58:36.400 T:25268   debug <general>: [script.trakt] resources.lib.service: Queued dispatch: {'action': 'manualSync', 'silent': False, 'library': 'all'}
2024-10-04 15:58:36.400 T:25268   debug <general>: [script.trakt] resources.lib.service: Dispatch: {'action': 'manualSync', 'silent': False, 'library': 'all'}
2024-10-04 15:58:36.400 T:25268   debug <general>: [script.trakt] resources.lib.service: Performing a manual sync.
2024-10-04 15:58:36.401 T:6620    debug <general>: [script.trakt] resources.lib.sync: Starting synchronization with Trakt.tv
2024-10-04 15:58:36.401 T:6620    debug <general>: DialogProgress::Open called 
2024-10-04 15:58:36.401 T:7084    debug <general>: ------ Window Init (DialogConfirm.xml) ------
2024-10-04 15:58:36.401 T:7084     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-10-04 15:58:36.403 T:6620    debug <general>: [script.trakt] resources.lib.syncMovies: [Movies Sync] Getting movie data from Kodi
2024-10-04 15:58:36.673 T:6620    debug <general>: [script.trakt] resources.lib.syncMovies: [Movies Sync] Getting movie collection from Trakt.tv
2024-10-04 15:58:36.675 T:6620    debug <general>: [script.trakt] urllib3.connectionpool: Starting new HTTPS connection (1): api.trakt.tv:443
2024-10-04 15:58:36.870 T:6620    debug <general>: [script.trakt] urllib3.connectionpool: https://api.trakt.tv:443 "GET /sync/collection/movies HTTP/1.1" 200 None
2024-10-04 15:58:37.362 T:6620    debug <general>: [script.trakt] urllib3.connectionpool: https://api.trakt.tv:443 "GET /sync/watched/movies HTTP/1.1" 200 None
2024-10-04 15:58:37.695 T:6620    debug <general>: [script.trakt] urllib3.connectionpool: https://api.trakt.tv:443 "GET /sync/ratings/movies HTTP/1.1" 200 None
2024-10-04 15:58:38.368 T:6620    debug <general>: [script.trakt] resources.lib.syncMovies: [Movies Sync] Trakt.tv movie playcount is up to date
2024-10-04 15:58:39.000 T:6620    debug <general>: [script.trakt] resources.lib.syncMovies: [Movies Sync] 259 movie(s) playcount will be updated in Kodi
2024-10-04 15:58:39.001 T:6620    debug <general>: [script.trakt] resources.lib.syncMovies: [Movies Sync] Movies to add: _--LIST--_
2024-10-04 15:58:39.011 T:6620    error <general>: Exception in thread 
2024-10-04 15:58:39.011 T:6620    error <general>: trakt-sync
2024-10-04 15:58:39.011 T:6620    error <general>: :
                                                   
2024-10-04 15:58:39.011 T:6620    error <general>: Traceback (most recent call last):
                                                   
2024-10-04 15:58:39.011 T:6620    error <general>:   File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.1.500.0_x64__4n2hpmxwrvr6p\system\python\Lib\threading.py", line 932, in _bootstrap_inner
                                                   
2024-10-04 15:58:39.011 T:6620    error <general>:     
2024-10-04 15:58:39.011 T:6620    error <general>: self.run()
2024-10-04 15:58:39.011 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.011 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\service.py", line 424, in run
                                                   
2024-10-04 15:58:39.011 T:6620    error <general>:     
2024-10-04 15:58:39.011 T:6620    error <general>: sync.sync()
2024-10-04 15:58:39.011 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.011 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\sync.py", line 60, in sync
                                                   
2024-10-04 15:58:39.012 T:6620    error <general>:     
2024-10-04 15:58:39.012 T:6620    error <general>: syncMovies.SyncMovies(self, progress)
2024-10-04 15:58:39.012 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.012 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\syncMovies.py", line 51, in __init__
                                                   
2024-10-04 15:58:39.012 T:6620    error <general>:     
2024-10-04 15:58:39.012 T:6620    error <general>: self.__addMoviesToKodiWatched(traktMovies, kodiMovies, 70, 80)
2024-10-04 15:58:39.012 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.012 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\syncMovies.py", line 390, in __addMoviesToKodiWatched
                                                   
2024-10-04 15:58:39.012 T:6620    error <general>:     
2024-10-04 15:58:39.012 T:6620    error <general>: [
2024-10-04 15:58:39.012 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.012 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\syncMovies.py", line 397, in <listcomp>
                                                   
2024-10-04 15:58:39.013 T:6620    error <general>:     
2024-10-04 15:58:39.013 T:6620    error <general>: "lastplayed": utilities.convertUtcToDateTime(
2024-10-04 15:58:39.013 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.013 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\utilities.py", line 243, in convertUtcToDateTime
                                                   
2024-10-04 15:58:39.013 T:6620    error <general>:     
2024-10-04 15:58:39.013 T:6620    error <general>: local = utc.astimezone(tzlocal())
2024-10-04 15:58:39.013 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.013 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\_common.py", line 144, in fromutc
                                                   
2024-10-04 15:58:39.013 T:6620    error <general>:     
2024-10-04 15:58:39.013 T:6620    error <general>: return f(self, dt)
2024-10-04 15:58:39.013 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.013 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\_common.py", line 261, in fromutc
                                                   
2024-10-04 15:58:39.014 T:6620    error <general>:     
2024-10-04 15:58:39.014 T:6620    error <general>: _fold = self._fold_status(dt, dt_wall)
2024-10-04 15:58:39.014 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.014 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\_common.py", line 196, in _fold_status
                                                   
2024-10-04 15:58:39.014 T:6620    error <general>:     
2024-10-04 15:58:39.014 T:6620    error <general>: if self.is_ambiguous(dt_wall):
2024-10-04 15:58:39.014 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.014 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 254, in is_ambiguous
                                                   
2024-10-04 15:58:39.014 T:6620    error <general>:     
2024-10-04 15:58:39.014 T:6620    error <general>: naive_dst = self._naive_is_dst(dt)
2024-10-04 15:58:39.014 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.014 T:6620    error <general>:   File "C:\Users\Toma\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 260, in _naive_is_dst
                                                   
2024-10-04 15:58:39.014 T:6620    error <general>:     
2024-10-04 15:58:39.014 T:6620    error <general>: return time.localtime(timestamp + time.timezone).tm_isdst
2024-10-04 15:58:39.014 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.015 T:6620    error <general>: OSError
2024-10-04 15:58:39.015 T:6620    error <general>: : 
2024-10-04 15:58:39.015 T:6620    error <general>: [Errno 22] Invalid argument
2024-10-04 15:58:39.015 T:6620    error <general>: 
                                                   
2024-10-04 15:58:39.015 T:6620    debug <general>: .
2024-10-04 15:58:42.691 T:7084     info <general>: Skipped 1 duplicate messages..
2024-10-04 15:58:42.691 T:7084    debug <general>: ------ Window Deinit (Pointer.xml) ------
2024-10-04 15:59:04.901 T:27080   debug <general>: Thread JobWorker 27080 terminating (autodelete)
2024-10-04 15:59:04.912 T:27340   debug <general>: Thread JobWorker 27340 terminating (autodelete)
2024-10-04 15:59:25.456 T:7084    debug <general>: ------ Window Init (Pointer.xml) ------ 

```

**Comment by razzeee** [comment]
Probably duplicate of https://github.com/trakt/script.trakt/issues/630#issuecomment-1865003044

**Comment by AwakenCX** [comment]
Thanks for the quick reply, unfortunately it doesn't solve my problem.
I'm a bit desperate..


Still stuck at :
![image](https://github.com/user-attachments/assets/8074eeff-26ae-42a4-a5fa-be431596b30a)

**Comment by AwakenCX** [comment]
Up ?

**Comment by AwakenCX** [comment]
**I finally solved my problem!** 

It seems that 2 of my movies bugs.
I tried to integrate my films 10 by 10 and I realized that “Modern times (1936)” and “Dumbo (2019)” didn't want to synchronize.

I simply deleted these 2 films and now all my films are in sync!
